// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ScriptiumBackend.Db;

#nullable disable

namespace ScriptiumBackend.Migrations
{
    [DbContext(typeof(ScriptiumDbContext))]
    [Migration("20260102162058_cache_meachanism")]
    partial class cache_meachanism
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ChapterMeaning", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<short>("ChapterId")
                        .HasColumnType("smallint")
                        .HasColumnName("i_q_chapter_id");

                    b.Property<long>("MeaningId")
                        .HasColumnType("bigint")
                        .HasColumnName("meaning_id");

                    b.HasKey("Id");

                    b.HasIndex("MeaningId");

                    b.HasIndex("ChapterId", "MeaningId")
                        .IsUnique();

                    b.ToTable("i_q_chapter_meanings", (string)null);
                });

            modelBuilder.Entity("MeaningScripture", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("MeaningId")
                        .HasColumnType("bigint")
                        .HasColumnName("meaning_id");

                    b.Property<short>("ScriptureId")
                        .HasColumnType("smallint")
                        .HasColumnName("scripture_id");

                    b.HasKey("Id");

                    b.HasIndex("MeaningId");

                    b.HasIndex("ScriptureId", "MeaningId")
                        .IsUnique();

                    b.ToTable("c_scripture_meanings", (string)null);
                });

            modelBuilder.Entity("MeaningWord", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("MeaningId")
                        .HasColumnType("bigint")
                        .HasColumnName("meaning_id");

                    b.Property<int>("WordId")
                        .HasColumnType("integer")
                        .HasColumnName("i_q_word_id");

                    b.HasKey("Id");

                    b.HasIndex("MeaningId");

                    b.HasIndex("WordId", "MeaningId")
                        .IsUnique();

                    b.ToTable("i_q_word_meanings", (string)null);
                });

            modelBuilder.Entity("ScriptiumBackend.Model.Common.Chapter", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("c_chapter");
                });

            modelBuilder.Entity("ScriptiumBackend.Model.Common.Root", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("character varying(25)")
                        .HasColumnName("content");

                    b.Property<string>("Latin")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("character varying(25)")
                        .HasColumnName("latin");

                    b.HasKey("Id");

                    b.ToTable("c_root");
                });

            modelBuilder.Entity("ScriptiumBackend.Model.Common.Scripture", b =>
                {
                    b.Property<short>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<short>("Id"));

                    b.Property<char>("Code")
                        .HasColumnType("character(1)")
                        .HasColumnName("code");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("c_scripture");
                });

            modelBuilder.Entity("ScriptiumBackend.Model.Common.Verse", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("Number")
                        .HasColumnType("integer")
                        .HasColumnName("number");

                    b.HasKey("Id");

                    b.ToTable("c_verse");
                });

            modelBuilder.Entity("ScriptiumBackend.Model.Common.Word", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<int>("SequenceNumber")
                        .HasColumnType("integer")
                        .HasColumnName("sequence_number");

                    b.Property<long>("VerseId")
                        .HasColumnType("bigint")
                        .HasColumnName("verse_id");

                    b.HasKey("Id");

                    b.HasIndex("VerseId");

                    b.ToTable("c_word");
                });

            modelBuilder.Entity("ScriptiumBackend.Model.Islam.Quranic.Chapter", b =>
                {
                    b.Property<short>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<short>("Id"));

                    b.Property<int>("Sequence")
                        .HasColumnType("integer")
                        .HasColumnName("sequence");

                    b.Property<long>("chapter_id")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("chapter_id")
                        .IsUnique();

                    b.ToTable("i_q_chapter");
                });

            modelBuilder.Entity("ScriptiumBackend.Model.Islam.Quranic.Verse", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Simple")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("character varying(5000)")
                        .HasColumnName("simple");

                    b.Property<string>("SimpleClean")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("character varying(5000)")
                        .HasColumnName("simple_clean");

                    b.Property<string>("SimpleMinimal")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("character varying(5000)")
                        .HasColumnName("simple_minimal");

                    b.Property<string>("SimplePlain")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("character varying(5000)")
                        .HasColumnName("simple_plain");

                    b.Property<string>("Uthmani")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("character varying(5000)")
                        .HasColumnName("uthmani");

                    b.Property<string>("UthmaniMinimal")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("character varying(5000)")
                        .HasColumnName("uthmani_minimal");

                    b.Property<short>("i_q_chapter_id")
                        .HasColumnType("smallint");

                    b.Property<long>("verse_id")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("i_q_chapter_id");

                    b.HasIndex("verse_id")
                        .IsUnique();

                    b.ToTable("i_q_verse");
                });

            modelBuilder.Entity("ScriptiumBackend.Model.Islam.Quranic.Word", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<long>("word_c_id")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("word_c_id");

                    b.ToTable("i_q_word");
                });

            modelBuilder.Entity("ScriptiumBackend.Model.Shared.Language", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("code");

                    b.Property<string>("EnglishName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("english_name");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("s_language");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "en",
                            EnglishName = "English",
                            Name = "English"
                        });
                });

            modelBuilder.Entity("ScriptiumBackend.Model.Shared.Meaning", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("content");

                    b.Property<int>("LanguageId")
                        .HasColumnType("integer")
                        .HasColumnName("language_id");

                    b.HasKey("Id");

                    b.HasIndex("LanguageId");

                    b.ToTable("s_meaning");
                });

            modelBuilder.Entity("ScriptiumBackend.Model.Shared.Node", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long?>("parent_id")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("parent_id");

                    b.ToTable("c_node");
                });

            modelBuilder.Entity("ScriptiumBackend.Model.Shared.Transliteration", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<int>("language_id")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("language_id");

                    b.ToTable("s_transliteration");
                });

            modelBuilder.Entity("ScriptiumBackend.Model.Util.Cache", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("data");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("url");

                    b.HasKey("Id");

                    b.HasIndex("Url")
                        .IsUnique();

                    b.ToTable("u_cache", (string)null);
                });

            modelBuilder.Entity("ScriptiumBackend.Model.Util.CacheRecord", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("FetchedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fetched_at");

                    b.Property<long>("cache_id")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("cache_id");

                    b.ToTable("u_cache_record", (string)null);
                });

            modelBuilder.Entity("TransliterationWord", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("TransliterationId")
                        .HasColumnType("bigint")
                        .HasColumnName("transliteration_id");

                    b.Property<int>("WordId")
                        .HasColumnType("integer")
                        .HasColumnName("i_q_word_id");

                    b.HasKey("Id");

                    b.HasIndex("TransliterationId");

                    b.HasIndex("WordId", "TransliterationId")
                        .IsUnique();

                    b.ToTable("i_q_word_transliterations", (string)null);
                });

            modelBuilder.Entity("c_mm_root_word", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("RootsId")
                        .HasColumnType("bigint")
                        .HasColumnName("root_id");

                    b.Property<long>("WordsId")
                        .HasColumnType("bigint")
                        .HasColumnName("word_id");

                    b.HasKey("Id");

                    b.HasIndex("WordsId");

                    b.HasIndex("RootsId", "WordsId")
                        .IsUnique();

                    b.ToTable("c_mm_root_word");
                });

            modelBuilder.Entity("ChapterMeaning", b =>
                {
                    b.HasOne("ScriptiumBackend.Model.Islam.Quranic.Chapter", null)
                        .WithMany()
                        .HasForeignKey("ChapterId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("ScriptiumBackend.Model.Shared.Meaning", null)
                        .WithMany()
                        .HasForeignKey("MeaningId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("MeaningScripture", b =>
                {
                    b.HasOne("ScriptiumBackend.Model.Shared.Meaning", null)
                        .WithMany()
                        .HasForeignKey("MeaningId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("ScriptiumBackend.Model.Common.Scripture", null)
                        .WithMany()
                        .HasForeignKey("ScriptureId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("MeaningWord", b =>
                {
                    b.HasOne("ScriptiumBackend.Model.Shared.Meaning", null)
                        .WithMany()
                        .HasForeignKey("MeaningId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("ScriptiumBackend.Model.Islam.Quranic.Word", null)
                        .WithMany()
                        .HasForeignKey("WordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ScriptiumBackend.Model.Common.Word", b =>
                {
                    b.HasOne("ScriptiumBackend.Model.Common.Verse", "Verse")
                        .WithMany("Words")
                        .HasForeignKey("VerseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Verse");
                });

            modelBuilder.Entity("ScriptiumBackend.Model.Islam.Quranic.Chapter", b =>
                {
                    b.HasOne("ScriptiumBackend.Model.Common.Chapter", "ChapterC")
                        .WithOne()
                        .HasForeignKey("ScriptiumBackend.Model.Islam.Quranic.Chapter", "chapter_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChapterC");
                });

            modelBuilder.Entity("ScriptiumBackend.Model.Islam.Quranic.Verse", b =>
                {
                    b.HasOne("ScriptiumBackend.Model.Islam.Quranic.Chapter", "Chapter")
                        .WithMany("Verses")
                        .HasForeignKey("i_q_chapter_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ScriptiumBackend.Model.Common.Verse", "VerseC")
                        .WithOne()
                        .HasForeignKey("ScriptiumBackend.Model.Islam.Quranic.Verse", "verse_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Chapter");

                    b.Navigation("VerseC");
                });

            modelBuilder.Entity("ScriptiumBackend.Model.Islam.Quranic.Word", b =>
                {
                    b.HasOne("ScriptiumBackend.Model.Common.Word", "WordC")
                        .WithMany()
                        .HasForeignKey("word_c_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WordC");
                });

            modelBuilder.Entity("ScriptiumBackend.Model.Shared.Meaning", b =>
                {
                    b.HasOne("ScriptiumBackend.Model.Shared.Language", "Language")
                        .WithMany()
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Language");
                });

            modelBuilder.Entity("ScriptiumBackend.Model.Shared.Node", b =>
                {
                    b.HasOne("ScriptiumBackend.Model.Shared.Node", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("parent_id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("ScriptiumBackend.Model.Shared.Transliteration", b =>
                {
                    b.HasOne("ScriptiumBackend.Model.Shared.Language", "Language")
                        .WithMany()
                        .HasForeignKey("language_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Language");
                });

            modelBuilder.Entity("ScriptiumBackend.Model.Util.CacheRecord", b =>
                {
                    b.HasOne("ScriptiumBackend.Model.Util.Cache", "Cache")
                        .WithMany("Records")
                        .HasForeignKey("cache_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cache");
                });

            modelBuilder.Entity("TransliterationWord", b =>
                {
                    b.HasOne("ScriptiumBackend.Model.Shared.Transliteration", null)
                        .WithMany()
                        .HasForeignKey("TransliterationId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("ScriptiumBackend.Model.Islam.Quranic.Word", null)
                        .WithMany()
                        .HasForeignKey("WordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("c_mm_root_word", b =>
                {
                    b.HasOne("ScriptiumBackend.Model.Common.Root", null)
                        .WithMany()
                        .HasForeignKey("RootsId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ScriptiumBackend.Model.Common.Word", null)
                        .WithMany()
                        .HasForeignKey("WordsId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("ScriptiumBackend.Model.Common.Verse", b =>
                {
                    b.Navigation("Words");
                });

            modelBuilder.Entity("ScriptiumBackend.Model.Islam.Quranic.Chapter", b =>
                {
                    b.Navigation("Verses");
                });

            modelBuilder.Entity("ScriptiumBackend.Model.Shared.Node", b =>
                {
                    b.Navigation("Children");
                });

            modelBuilder.Entity("ScriptiumBackend.Model.Util.Cache", b =>
                {
                    b.Navigation("Records");
                });
#pragma warning restore 612, 618
        }
    }
}
