// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Pgvector;
using ScriptiumBackend.Db;

#nullable disable

namespace ScriptiumBackend.Migrations
{
    [DbContext(typeof(ScriptiumDbContext))]
    partial class ScriptiumDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "pg_trgm");
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "vector");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AuthorMeaning", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("AuthorId")
                        .HasColumnType("bigint")
                        .HasColumnName("s_author_id");

                    b.Property<long>("MeaningId")
                        .HasColumnType("bigint")
                        .HasColumnName("s_meaning_id");

                    b.HasKey("Id");

                    b.HasIndex("MeaningId");

                    b.HasIndex("AuthorId", "MeaningId")
                        .IsUnique();

                    b.ToTable("mm_s_authorName__a_translations", (string)null);
                });

            modelBuilder.Entity("AuthorTranslation", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("AuthorId")
                        .HasColumnType("bigint")
                        .HasColumnName("s_author_id");

                    b.Property<short>("TranslationId")
                        .HasColumnType("smallint")
                        .HasColumnName("s_translation_id");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("TranslationId", "AuthorId")
                        .IsUnique();

                    b.ToTable("mm_s_translation__s_author", (string)null);
                });

            modelBuilder.Entity("ChapterMeaning", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<short>("ChapterId")
                        .HasColumnType("smallint")
                        .HasColumnName("i_q_chapter_id");

                    b.Property<long>("MeaningId")
                        .HasColumnType("bigint")
                        .HasColumnName("s_meaning_id");

                    b.HasKey("Id");

                    b.HasIndex("MeaningId");

                    b.HasIndex("ChapterId", "MeaningId")
                        .IsUnique();

                    b.ToTable("mm_i_q_chapter__s_meanings", (string)null);
                });

            modelBuilder.Entity("MeaningScripture", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("MeaningId")
                        .HasColumnType("bigint")
                        .HasColumnName("s_meaning_id");

                    b.Property<short>("ScriptureId")
                        .HasColumnType("smallint")
                        .HasColumnName("s_scripture_id");

                    b.HasKey("Id");

                    b.HasIndex("MeaningId");

                    b.HasIndex("ScriptureId", "MeaningId")
                        .IsUnique();

                    b.ToTable("mm_s_scripture__s_meanings", (string)null);
                });

            modelBuilder.Entity("MeaningWord", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("MeaningId")
                        .HasColumnType("bigint")
                        .HasColumnName("s_meaning_id");

                    b.Property<int>("WordId")
                        .HasColumnType("integer")
                        .HasColumnName("i_q_word_id");

                    b.HasKey("Id");

                    b.HasIndex("MeaningId");

                    b.HasIndex("WordId", "MeaningId")
                        .IsUnique();

                    b.ToTable("mm_i_q_word__s_meanings", (string)null);
                });

            modelBuilder.Entity("ScriptiumBackend.Model.Abstract.Chapter", b =>
                {
                    b.Property<short>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<short>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("a_chapter");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("ScriptiumBackend.Model.Abstract.Root", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("text");

                    b.HasKey("Id");

                    b.HasIndex("Text")
                        .IsUnique();

                    b.ToTable("a_root");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("ScriptiumBackend.Model.Abstract.Translation", b =>
                {
                    b.Property<short>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<short>("Id"));

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date")
                        .HasColumnName("published_at");

                    b.Property<string>("Description")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<int>("s_language_id")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("s_language_id");

                    b.ToTable("a_translation");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("ScriptiumBackend.Model.Abstract.Verse", b =>
                {
                    b.Property<short>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<short>("Id"));

                    b.Property<int>("Number")
                        .HasColumnType("integer")
                        .HasColumnName("number");

                    b.HasKey("Id");

                    b.ToTable("a_verse");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("ScriptiumBackend.Model.Abstract.Word", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Sequence")
                        .HasColumnType("integer")
                        .HasColumnName("sequence");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("text");

                    b.HasKey("Id");

                    b.ToTable("a_word");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("ScriptiumBackend.Model.Sealed.Author", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("name");

                    b.Property<string>("Url")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("url");

                    b.Property<int>("s_language_id")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("s_language_id");

                    b.ToTable("s_author");
                });

            modelBuilder.Entity("ScriptiumBackend.Model.Sealed.Footnote", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("Index")
                        .HasColumnType("bigint")
                        .HasColumnName("index");

                    b.Property<string>("Indicator")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("indicator");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("text");

                    b.Property<long>("a_translationUnit_id")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("a_translationUnit_id");

                    b.ToTable("s_footnote");
                });

            modelBuilder.Entity("ScriptiumBackend.Model.Sealed.Language", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("code");

                    b.Property<string>("EnglishName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("english_name");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("s_language");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "en",
                            EnglishName = "English",
                            Name = "English"
                        });
                });

            modelBuilder.Entity("ScriptiumBackend.Model.Sealed.Meaning", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("content");

                    b.Property<int>("s_language_id")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("s_language_id");

                    b.ToTable("s_meaning");
                });

            modelBuilder.Entity("ScriptiumBackend.Model.Sealed.Scripture", b =>
                {
                    b.Property<short>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<short>("Id"));

                    b.Property<char>("Code")
                        .HasColumnType("character(1)")
                        .HasColumnName("code");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("s_scripture");
                });

            modelBuilder.Entity("ScriptiumBackend.Model.Sealed.Transliteration", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(2500)
                        .HasColumnType("character varying(2500)")
                        .HasColumnName("content");

                    b.Property<int>("s_language_id")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("s_language_id");

                    b.ToTable("s_transliteration");
                });

            modelBuilder.Entity("ScriptiumBackend.Model.Util.Cache", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("data");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("url");

                    b.HasKey("Id");

                    b.HasIndex("Url")
                        .IsUnique();

                    b.ToTable("u_cache", (string)null);
                });

            modelBuilder.Entity("ScriptiumBackend.Model.Util.CacheRecord", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("FetchedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fetched_at");

                    b.Property<long>("cache_id")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("cache_id");

                    b.ToTable("u_cache_record", (string)null);
                });

            modelBuilder.Entity("ScriptiumBackend.Model.Util.SearchableItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<Vector>("Embedding")
                        .HasColumnType("vector(768)")
                        .HasColumnName("embedding");

                    b.Property<DateTime?>("LastEmbeddedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_embedded_at");

                    b.HasKey("Id");

                    b.ToTable("u_searchable_item", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("TransliterationVerse", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("TransliterationId")
                        .HasColumnType("bigint")
                        .HasColumnName("s_transliteration_id");

                    b.Property<short>("VerseId")
                        .HasColumnType("smallint")
                        .HasColumnName("i_q_verse_id");

                    b.HasKey("Id");

                    b.HasIndex("VerseId");

                    b.HasIndex("TransliterationId", "VerseId")
                        .IsUnique();

                    b.ToTable("mm_i_q_verse__s_transliteration", (string)null);
                });

            modelBuilder.Entity("TransliterationWord", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("TransliterationId")
                        .HasColumnType("bigint")
                        .HasColumnName("s_transliteration_id");

                    b.Property<int>("WordId")
                        .HasColumnType("integer")
                        .HasColumnName("i_q_word_id");

                    b.HasKey("Id");

                    b.HasIndex("TransliterationId");

                    b.HasIndex("WordId", "TransliterationId")
                        .IsUnique();

                    b.ToTable("mm_i_q_word__s_transliterations", (string)null);
                });

            modelBuilder.Entity("mm_i_q_root__i_q_word", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("RootsId")
                        .HasColumnType("integer")
                        .HasColumnName("i_q_root_id");

                    b.Property<int>("WordsId")
                        .HasColumnType("integer")
                        .HasColumnName("i_q_word_id");

                    b.HasKey("Id");

                    b.HasIndex("WordsId");

                    b.HasIndex("RootsId", "WordsId")
                        .IsUnique();

                    b.ToTable("mm_i_q_root__i_q_word");
                });

            modelBuilder.Entity("ScriptiumBackend.Model.Derived.Islam.Quranic.Chapter", b =>
                {
                    b.HasBaseType("ScriptiumBackend.Model.Abstract.Chapter");

                    b.Property<int>("Sequence")
                        .HasColumnType("integer")
                        .HasColumnName("sequence");

                    b.ToTable("i_q_chapter");
                });

            modelBuilder.Entity("ScriptiumBackend.Model.Derived.Islam.Quranic.Root", b =>
                {
                    b.HasBaseType("ScriptiumBackend.Model.Abstract.Root");

                    b.Property<string>("TextInLatin")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("character varying(25)")
                        .HasColumnName("latin");

                    b.ToTable("i_q_root");
                });

            modelBuilder.Entity("ScriptiumBackend.Model.Derived.Islam.Quranic.Translation", b =>
                {
                    b.HasBaseType("ScriptiumBackend.Model.Abstract.Translation");

                    b.ToTable("i_q_translation");
                });

            modelBuilder.Entity("ScriptiumBackend.Model.Derived.Islam.Quranic.Verse", b =>
                {
                    b.HasBaseType("ScriptiumBackend.Model.Abstract.Verse");

                    b.Property<string>("Simple")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("character varying(5000)")
                        .HasColumnName("simple");

                    b.Property<string>("SimpleClean")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("character varying(5000)")
                        .HasColumnName("simple_clean");

                    b.Property<string>("SimpleMinimal")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("character varying(5000)")
                        .HasColumnName("simple_minimal");

                    b.Property<string>("SimplePlain")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("character varying(5000)")
                        .HasColumnName("simple_plain");

                    b.Property<string>("Uthmani")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("character varying(5000)")
                        .HasColumnName("uthmani");

                    b.Property<string>("UthmaniMinimal")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("character varying(5000)")
                        .HasColumnName("uthmani_minimal");

                    b.Property<short>("i_q_chapter_id")
                        .HasColumnType("smallint");

                    b.HasIndex("i_q_chapter_id");

                    b.ToTable("i_q_verse");
                });

            modelBuilder.Entity("ScriptiumBackend.Model.Derived.Islam.Quranic.Word", b =>
                {
                    b.HasBaseType("ScriptiumBackend.Model.Abstract.Word");

                    b.Property<short>("i_q_verse_id")
                        .HasColumnType("smallint");

                    b.HasIndex("i_q_verse_id");

                    b.ToTable("i_q_word");
                });

            modelBuilder.Entity("ScriptiumBackend.Model.Abstract.TranslationUnit", b =>
                {
                    b.HasBaseType("ScriptiumBackend.Model.Util.SearchableItem");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(2500)
                        .HasColumnType("character varying(2500)")
                        .HasColumnName("text");

                    b.Property<int>("s_language_id")
                        .HasColumnType("integer");

                    b.HasIndex("Text");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Text"), "gin");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("Text"), new[] { "gin_trgm_ops" });

                    b.HasIndex("s_language_id");

                    b.ToTable("a_translationUnit");
                });

            modelBuilder.Entity("ScriptiumBackend.Model.Derived.Islam.Quranic.VerseTranslation", b =>
                {
                    b.HasBaseType("ScriptiumBackend.Model.Abstract.TranslationUnit");

                    b.Property<short>("i_q_translation_id")
                        .HasColumnType("smallint");

                    b.Property<short>("i_q_verse_id")
                        .HasColumnType("smallint");

                    b.HasIndex("i_q_translation_id");

                    b.HasIndex("i_q_verse_id");

                    b.ToTable("i_q_verse_translation", (string)null);
                });

            modelBuilder.Entity("AuthorMeaning", b =>
                {
                    b.HasOne("ScriptiumBackend.Model.Sealed.Author", null)
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ScriptiumBackend.Model.Sealed.Meaning", null)
                        .WithMany()
                        .HasForeignKey("MeaningId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("AuthorTranslation", b =>
                {
                    b.HasOne("ScriptiumBackend.Model.Sealed.Author", null)
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ScriptiumBackend.Model.Abstract.Translation", null)
                        .WithMany()
                        .HasForeignKey("TranslationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ChapterMeaning", b =>
                {
                    b.HasOne("ScriptiumBackend.Model.Derived.Islam.Quranic.Chapter", null)
                        .WithMany()
                        .HasForeignKey("ChapterId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("ScriptiumBackend.Model.Sealed.Meaning", null)
                        .WithMany()
                        .HasForeignKey("MeaningId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("MeaningScripture", b =>
                {
                    b.HasOne("ScriptiumBackend.Model.Sealed.Meaning", null)
                        .WithMany()
                        .HasForeignKey("MeaningId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("ScriptiumBackend.Model.Sealed.Scripture", null)
                        .WithMany()
                        .HasForeignKey("ScriptureId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("MeaningWord", b =>
                {
                    b.HasOne("ScriptiumBackend.Model.Sealed.Meaning", null)
                        .WithMany()
                        .HasForeignKey("MeaningId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("ScriptiumBackend.Model.Derived.Islam.Quranic.Word", null)
                        .WithMany()
                        .HasForeignKey("WordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ScriptiumBackend.Model.Abstract.Translation", b =>
                {
                    b.HasOne("ScriptiumBackend.Model.Sealed.Language", "Language")
                        .WithMany()
                        .HasForeignKey("s_language_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Language");
                });

            modelBuilder.Entity("ScriptiumBackend.Model.Sealed.Author", b =>
                {
                    b.HasOne("ScriptiumBackend.Model.Sealed.Language", "Language")
                        .WithMany()
                        .HasForeignKey("s_language_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Language");
                });

            modelBuilder.Entity("ScriptiumBackend.Model.Sealed.Footnote", b =>
                {
                    b.HasOne("ScriptiumBackend.Model.Abstract.TranslationUnit", "Translation")
                        .WithMany("Footnotes")
                        .HasForeignKey("a_translationUnit_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Translation");
                });

            modelBuilder.Entity("ScriptiumBackend.Model.Sealed.Meaning", b =>
                {
                    b.HasOne("ScriptiumBackend.Model.Sealed.Language", "Language")
                        .WithMany()
                        .HasForeignKey("s_language_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Language");
                });

            modelBuilder.Entity("ScriptiumBackend.Model.Sealed.Transliteration", b =>
                {
                    b.HasOne("ScriptiumBackend.Model.Sealed.Language", "Language")
                        .WithMany()
                        .HasForeignKey("s_language_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Language");
                });

            modelBuilder.Entity("ScriptiumBackend.Model.Util.CacheRecord", b =>
                {
                    b.HasOne("ScriptiumBackend.Model.Util.Cache", "Cache")
                        .WithMany("Records")
                        .HasForeignKey("cache_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cache");
                });

            modelBuilder.Entity("TransliterationVerse", b =>
                {
                    b.HasOne("ScriptiumBackend.Model.Sealed.Transliteration", null)
                        .WithMany()
                        .HasForeignKey("TransliterationId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("ScriptiumBackend.Model.Derived.Islam.Quranic.Verse", null)
                        .WithMany()
                        .HasForeignKey("VerseId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("TransliterationWord", b =>
                {
                    b.HasOne("ScriptiumBackend.Model.Sealed.Transliteration", null)
                        .WithMany()
                        .HasForeignKey("TransliterationId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("ScriptiumBackend.Model.Derived.Islam.Quranic.Word", null)
                        .WithMany()
                        .HasForeignKey("WordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("mm_i_q_root__i_q_word", b =>
                {
                    b.HasOne("ScriptiumBackend.Model.Derived.Islam.Quranic.Root", null)
                        .WithMany()
                        .HasForeignKey("RootsId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ScriptiumBackend.Model.Derived.Islam.Quranic.Word", null)
                        .WithMany()
                        .HasForeignKey("WordsId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("ScriptiumBackend.Model.Derived.Islam.Quranic.Chapter", b =>
                {
                    b.HasOne("ScriptiumBackend.Model.Abstract.Chapter", null)
                        .WithOne()
                        .HasForeignKey("ScriptiumBackend.Model.Derived.Islam.Quranic.Chapter", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ScriptiumBackend.Model.Derived.Islam.Quranic.Root", b =>
                {
                    b.HasOne("ScriptiumBackend.Model.Abstract.Root", null)
                        .WithOne()
                        .HasForeignKey("ScriptiumBackend.Model.Derived.Islam.Quranic.Root", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ScriptiumBackend.Model.Derived.Islam.Quranic.Translation", b =>
                {
                    b.HasOne("ScriptiumBackend.Model.Abstract.Translation", null)
                        .WithOne()
                        .HasForeignKey("ScriptiumBackend.Model.Derived.Islam.Quranic.Translation", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ScriptiumBackend.Model.Derived.Islam.Quranic.Verse", b =>
                {
                    b.HasOne("ScriptiumBackend.Model.Abstract.Verse", null)
                        .WithOne()
                        .HasForeignKey("ScriptiumBackend.Model.Derived.Islam.Quranic.Verse", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ScriptiumBackend.Model.Derived.Islam.Quranic.Chapter", "Chapter")
                        .WithMany("Verses")
                        .HasForeignKey("i_q_chapter_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Chapter");
                });

            modelBuilder.Entity("ScriptiumBackend.Model.Derived.Islam.Quranic.Word", b =>
                {
                    b.HasOne("ScriptiumBackend.Model.Abstract.Word", null)
                        .WithOne()
                        .HasForeignKey("ScriptiumBackend.Model.Derived.Islam.Quranic.Word", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ScriptiumBackend.Model.Derived.Islam.Quranic.Verse", "Verse")
                        .WithMany("Words")
                        .HasForeignKey("i_q_verse_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Verse");
                });

            modelBuilder.Entity("ScriptiumBackend.Model.Abstract.TranslationUnit", b =>
                {
                    b.HasOne("ScriptiumBackend.Model.Util.SearchableItem", null)
                        .WithOne()
                        .HasForeignKey("ScriptiumBackend.Model.Abstract.TranslationUnit", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ScriptiumBackend.Model.Sealed.Language", "Language")
                        .WithMany()
                        .HasForeignKey("s_language_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Language");
                });

            modelBuilder.Entity("ScriptiumBackend.Model.Derived.Islam.Quranic.VerseTranslation", b =>
                {
                    b.HasOne("ScriptiumBackend.Model.Abstract.TranslationUnit", null)
                        .WithOne()
                        .HasForeignKey("ScriptiumBackend.Model.Derived.Islam.Quranic.VerseTranslation", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ScriptiumBackend.Model.Derived.Islam.Quranic.Translation", "Translation")
                        .WithMany("VerseTranslations")
                        .HasForeignKey("i_q_translation_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ScriptiumBackend.Model.Derived.Islam.Quranic.Verse", "Verse")
                        .WithMany("Translations")
                        .HasForeignKey("i_q_verse_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Translation");

                    b.Navigation("Verse");
                });

            modelBuilder.Entity("ScriptiumBackend.Model.Util.Cache", b =>
                {
                    b.Navigation("Records");
                });

            modelBuilder.Entity("ScriptiumBackend.Model.Derived.Islam.Quranic.Chapter", b =>
                {
                    b.Navigation("Verses");
                });

            modelBuilder.Entity("ScriptiumBackend.Model.Derived.Islam.Quranic.Translation", b =>
                {
                    b.Navigation("VerseTranslations");
                });

            modelBuilder.Entity("ScriptiumBackend.Model.Derived.Islam.Quranic.Verse", b =>
                {
                    b.Navigation("Translations");

                    b.Navigation("Words");
                });

            modelBuilder.Entity("ScriptiumBackend.Model.Abstract.TranslationUnit", b =>
                {
                    b.Navigation("Footnotes");
                });
#pragma warning restore 612, 618
        }
    }
}
